version: '3.8'

services:
  backend:
    build: ./backend
    container_name: genai-backend
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
    networks:
      - genai-network

  frontend:
    build: ./frontend
    container_name: genai-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - genai-network

networks:
  genai-network: